version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: trade-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: trade
    ports:
      - "3307:3307"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - trade-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 30s
      retries: 10
      interval: 30s

  redis:
    image: redis:alpine
    container_name: trade-redis
    command: redis-server --requirepass 1234
    ports:
      - "6379:6379"
    networks:
      - trade-network

  backend:
    build: .
    container_name: trade-backend
    depends_on:
      - mariadb
      - redis
    environment:
      DB_URL: jdbc:mariadb://mariadb:3306/trade
      DB_USERNAME: root
      DB_PASSWORD: 1234
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 1234
      JWT_SECRET: cf4de7f9512ed483a8b3d7cd02b896e655c79c5b7666dbdb5e91a405628f4304
      ACCESS_TOKEN_EXPIRE: 86400000
      REFRESH_TOKEN_EXPIRE: 172800000
    ports:
      - "8080:8080"
    networks:
      - trade-network

  frontend:
    build: ../front-service
    container_name: trade-frontend
    ports:
      - "3000:3000"
    networks:
      - trade-network
    environment:
      - NEXT_PUBLIC_URL=http://localhost
    volumes:
      - ../front-service/src:/app/src
  nginx-proxy:
    image: nginx:alpine
    container_name: trade-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - trade-network

networks:
  trade-network:
    driver: bridge

volumes:
  mariadb_data: